name: 'Your name here'
description: 'Provide a description here'
author: 'Thada'
inputs:
  mode:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  config:
    required: false
    description: 'input description here'
    default: 'default value if applicable'
  token:
    required: false
    description: 'personal access token'
  repo: 
    required: false
    description: 'repo'
  ref: 
    required: false
    description: 'ref'
    default: 'appsettings'
  path:
    required: false
    description: 'path to place app setting'
    default: '.'
  name:
    required: false
    description: 'App Service Name'
  resource-group:
    required: false
    description: 'resourceGroup'
  slot:
    required: false
    description: 'Source Slot of App Service'
  target-slot:
    required: false
    description: 'Target Slot of App Service'
  default-slot-setting:
    required: false
    description: 'defaultSlotSetting'
  default-sensitive:
    required: false
    description: 'defaultSensitive'
  app-settings-config:
    required: false
    description: 'AppSettings Configs'

runs:
  using: 'node16'
  main: 'dist/index.js'
