name: 'demo'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'releases/*'
env:
  config_dir: .github/workflows/config

jobs:

  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get-matrix.outputs.deployment-matrix }}
    steps:
    - uses: actions/checkout@v3
    - name: Export deployment matrix
      id: get-matrix
      run: |
        node ./index.js test-get-deploy-slots.json
      working-directory: ${{ env.config_dir }}

  set-slot-settings:
    name: ${{ format('⚙️ Set Slot | {0} - {1}', matrix.name, matrix.slot) }}
    needs: [ get-matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-matrix.outputs.result) }}
    steps:
      - run: |
          echo "1*** -> ${{ toJson(matrix) }}"
      # echo "2*** -> ${{ fromJson(matrix.appSettings) }}"
      # echo "3*** -> ${{ toJson(fromJson(matrix.appSettings)) }}"
      - uses: actions/checkout@v2
      # SP: github action az webapp swap
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
     
      - name: set-slot-settings
        uses:  ./
        with: 
          mode: set-deploy-slots
          swap-config: ${{ toJson(matrix) }}
          # name: ${{ matrix.name }}
          # resource-group: ${{ matrix.resourceGroup }}
          # slot: ${{ matrix.slot }}
          # target-slot: ${{ matrix.targetslot }}
          # default-slot-setting: ${{ matrix.defaultSlotSetting }}
          # default-sensitive: ${{ matrix.defaultSensitive }}
          # app-settings-config: ${{ toJson(fromJson(matrix.appSettings)) }}
          
