name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
env:
  config_dir: .github/workflows/config

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get-matrix.outputs.deployment-matrix }}
    steps:
    - uses: actions/checkout@v3
    - name: Export deployment matrix
      id: get-matrix
      run: |
        node ./index.js test-get-deploy-slots.json
      working-directory: ${{ env.config_dir }}

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: [ get-matrix ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          mode: get-deploy-slots
          config: ${{ needs.get-matrix.outputs.result }}
